//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_LinhKienDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GopY
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string Img { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Created_form { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Id_TaiKhoan { get; set; }
        public string DocumentPath { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
