//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_LinhKienDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LishSuMuaHnag
    {
        public int ID { get; set; }
        public System.DateTime NGAYMUA { get; set; }
        public Nullable<int> ID_TTGIOHANG { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> IDSANPHAM { get; set; }
        public string SDT { get; set; }
        public string TENNGUOINHAN { get; set; }
        public Nullable<bool> DATHANHTOAN { get; set; }
        public Nullable<long> TONGTIEN { get; set; }
    
        public virtual ThongTin_GioHang ThongTin_GioHang { get; set; }
    }
}
