//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_LinhKienDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thongtin_SP_Nhap
    {
        public int ID { get; set; }
        public string TENSP { get; set; }
        public double GIANHAP { get; set; }
        public System.DateTime NGAYNHAP { get; set; }
        public Nullable<int> IDNHACUNGCAP { get; set; }
        public Nullable<int> IDTAIKHOAN_ADMIN { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> IDLOAISP { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
    }
}
